name: Build APK - No Firebase No Signing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - run: chmod +x gradlew
      
      - run: |
          # Disable Firebase completely
          echo "" > app/google-services.json
          echo "" > app/src/debug/google-services.json
          echo "" > app/src/release/google-services.json
          
          # Create empty keystore
          mkdir -p ~/.android
          rm -rf  ~/.android/keystore.jks
          echo "dummy" > ~/.android/keystore.jks
      
      - run: ./gradlew assembleDebug
      
      - uses: actions/upload-artifact@v4
        with:
          name: han1meviewer-debug
          path: app/build/outputs/apk/debug/*.apk